"""
API endpoint for AI-powered email reply suggestions.

POST /api/emails/{email_id}/reply-suggestions
  → Returns 3 draft replies generated by the local LLM.
"""

import json
import re
import sqlite3

from fastapi import APIRouter, HTTPException, Depends, Query
from typing import Optional
from loguru import logger
import ollama as ollama_client

from config.settings import OLLAMA_MODEL, DB_PATH
from pipeline.reply_prompts import REPLY_SYSTEM_PROMPT, build_reply_prompt
from api.auth_jwt import get_current_user

router = APIRouter()


def _get_email_by_id(email_id: str) -> dict | None:
    """Fetch a single email record from SQLite by ID."""
    con = sqlite3.connect(str(DB_PATH))
    con.row_factory = sqlite3.Row
    try:
        cur = con.execute("SELECT * FROM emails WHERE id = ?", (email_id,))
        row = cur.fetchone()
        return dict(row) if row else None
    finally:
        con.close()


@router.post("/api/emails/{email_id}/reply-suggestions")
def generate_reply_suggestions(
    email_id: str,
    model_name: Optional[str] = Query(None, description="Override the Ollama model"),
    _user: str = Depends(get_current_user),
):
    """
    Generate 3 AI-powered reply suggestions for the specified email.

    Returns:
        { "email_id": "...", "model": "...", "suggestions": ["...", "...", "..."] }
    """
    # 1. Load the email from the database
    email = _get_email_by_id(email_id)
    if not email:
        raise HTTPException(status_code=404, detail=f"Email {email_id} not found.")

    # 2. Build the prompt
    subject = email.get("subject", "(no subject)")
    sender = f"{email.get('sender', '')} <{email.get('sender_email', '')}>"
    snippet = email.get("snippet", "") or email.get("body_preview", "")

    prompt = build_reply_prompt(subject=subject, sender=sender, snippet=snippet)
    model = model_name or OLLAMA_MODEL

    logger.info("Generating reply suggestions for email {} using model {}", email_id, model)

    # 3. Call Ollama
    try:
        response = ollama_client.chat(
            model=model,
            messages=[
                {"role": "system", "content": REPLY_SYSTEM_PROMPT},
                {"role": "user",   "content": prompt},
            ],
            options={"temperature": 0.7, "num_predict": 512},
        )

        raw = response["message"]["content"].strip()
        logger.debug("Reply LLM response: {}", raw[:300])

        # 4. Parse JSON response
        cleaned = re.sub(r"^```json\s*|```$", "", raw, flags=re.MULTILINE).strip()
        parsed = json.loads(cleaned)

        replies = parsed.get("replies", [])
        if not isinstance(replies, list) or len(replies) == 0:
            raise ValueError("LLM did not return a valid 'replies' array.")

        # Ensure exactly 3 replies
        replies = replies[:3]
        while len(replies) < 3:
            replies.append("I'll get back to you on this shortly.")

        return {
            "email_id": email_id,
            "model": model,
            "suggestions": replies,
        }

    except json.JSONDecodeError as e:
        logger.error("Failed to parse reply JSON: {}", e)
        # Return generic fallback replies
        return {
            "email_id": email_id,
            "model": model,
            "suggestions": [
                "Thank you for your email. I'll review and get back to you shortly.",
                "Thanks for reaching out! I'll take a look and respond soon.",
                "I appreciate your message. Let me review the details and follow up with you.",
            ],
            "fallback": True,
        }

    except Exception as e:
        logger.error("Reply generation failed for email {}: {}", email_id, e)
        raise HTTPException(
            status_code=500,
            detail=f"Failed to generate reply suggestions: {str(e)}",
        )
